- name: Install zed
  ansible.builtin.apt:
    name: zfs-zed
    state: present
    update_cache: yes
# PVE default: trim and scrub in /etc/cron.d/zfsutils-linux
# We setup ZED to send email alerts

- name: Configure zed
  ansible.builtin.template:
    src: zed.rc
    dest: /etc/zfs/zed.d/zed.rc
    owner: root
    group: root
    mode: "0600"
  notify:
    - Restart zed

- name: Enable zed
  ansible.builtin.systemd:
    name: zed
    enabled: yes
    state: started
