- name: Install required packages
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    state: present
    update_cache: yes

- name: Add Caddy GPG key
  ansible.builtin.shell:
    cmd: "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg"
    creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  register: caddy_gpg_key

- name: Add Caddy repository
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    dest: /etc/apt/sources.list.d/caddy-stable.list
    mode: "0644"
  register: caddy_repo

- name: Update apt cache
  apt:
    update_cache: yes
  when: caddy_gpg_key.changed or caddy_repo.changed

- name: Install Caddy
  apt:
    name: caddy
    state: present

- name: Template config
  template:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: 0644
  notify: Restart caddy
