- name: Docker compose up
  ansible.builtin.command: docker compose up -d --build --force-recreate --remove-orphans
  args:
    chdir: "{{ docker_compose_dir }}"

- name: Prune everything (including non-dangling images)
  ansible.builtin.command: docker system prune -af
