---
- name: Add Netdata repo
  ansible.builtin.apt_repository:
    repo: deb http://repo.netdata.cloud/repos/stable/{{ ansible_facts['distribution'] | lower }}/ {{ ansible_distribution_release }}/
    state: present
    filename: netdata

- name: Update repositories cache and install Netdata
  ansible.builtin.apt:
    name: netdata
    state: present
    update_cache: yes

- name: Template Netdata configuration
  template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: u=wrx,g=rx,o=r,+x
  notify: Restart Netdata

- name: Claim to Netdata Cloud if not already
  shell:
    cmd: netdata-claim.sh -token={{ claim_token }} -rooms={{ claim_rooms }} -url={{ claim_url }}
    creates: /var/lib/netdata/cloud.d/claimed_id
