version: "3"

services:
  ddddocr:
    image: lyc8503/ddddocr:v1
    ports:
      - "127.0.0.1:9898:80"

  webdis:
    image: registry.cn-shanghai.aliyuncs.com/lyc8503/webdis:0.1.21
    ports:
      - "127.0.0.1:7379:7379"

  subconverter:
    image: tindy2013/subconverter:0.8.1
    ports:
      - "127.0.0.1:25500:25500"
    command:
      [
        "/bin/sh",
        "-c",
        'cd /base && cp pref.example.toml pref.toml && sed -i "s/^api_mode = .*$$/api_mode = true/g" pref.toml && sed -i "s/^api_access_token = .*$$/api_access_token = "\"$$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 32)\""/g" pref.toml && cat pref.toml && subconverter',
      ]

  netdata:
    image: netdata/netdata
    ports:
      - "127.0.0.1:19999:19999"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
