- name: Install dependencies
  package:
    name:
      - curl
    state: present

- name: Ensure directory exist
  file:
    path: /opt/hy
    state: directory

- name: Install register script
  template:
    src: register.sh
    dest: /opt/hy/register.sh
    mode: 0755

- name: Setup cron job
  cron:
    name: Register hysteria2
    minute: "*/5"
    job: /opt/hy/register.sh
    state: present

- name: Get hysteria2 binary
  get_url:
    url: "https://download.hysteria.network/app/latest/hysteria-linux-{% if app_arch == '64' %}amd64{% else %}arm64{% endif %}"
    dest: /opt/hy/hysteria2
    mode: 0755

- name: Generate keypair
  shell:
    cmd: openssl req -x509 -newkey rsa:3072 -keyout server.key -out server.crt -sha256 -days 3650 -nodes -subj "/CN=server"
    chdir: /opt/hy/
    creates: /opt/hy/server.key

- name: Chmod privatekey
  file:
    path: /opt/hy/server.key
    mode: 0644

- name: Template hysteria2 config
  template:
    src: config.yml.j2
    dest: /opt/hy/config.yml
  notify:
    - Restart hysteria2

- name: Add systemd service
  template:
    src: hysteria2.service
    dest: /etc/systemd/system/hysteria2.service
  notify:
    - Restart hysteria2

- name: Start hysteria2
  systemd:
    name: hysteria2
    state: started
    daemon_reload: yes
    enabled: yes
