# This DN42 module is generated by Deepseek-V4-Pro and not reviewed by me so far
# It looks okay at first glance, but expect bugs!

from io import StringIO

from pyinfra import host
from pyinfra.operations import files, server

from dacite import from_dict
from schema import HostData
from inventory import DNET_NODES, DNET_CNAME, IBGP_NODES
from tasks._docker import ensure_docker

d = from_dict(HostData, host.data.dict())
dn = d.dn42

COMPOSE_DIR = "/opt/dn42"

my_ipv6 = dn.ipv6_addresses[0] if dn.ipv6_addresses else ""

# ============================================================
# Ensure Docker is installed
# ============================================================

ensure_docker()

# ============================================================
# Upload container source files (Dockerfile, entrypoint, etc.)
# Must happen before config generation so generated configs
# overwrite the uploaded placeholders.
# ============================================================

files.rsync(
    name="Upload dn42 container source files",
    src="files/dn42-containers/",
    dest=f"{COMPOSE_DIR}/containers/",
)

# ============================================================
# Generate WireGuard configs
# ============================================================

wireguard_dir = f"{COMPOSE_DIR}/containers/dn42-wireguard/wireguard"
wg_ports = []

# Clean up stale WG configs from removed peers
files.directory(
    name="Clean old WireGuard configs",
    path=wireguard_dir,
    present=False,
)
files.directory(
    name="Create fresh WireGuard config dir",
    path=wireguard_dir,
)

# eBGP peers
for name, peer in dn.ebgp_peers.items():
    safe = name.replace("-", "_")
    iface = f"dn42_{safe}"

    mtu_line = f"MTU = {peer.mtu}" if peer.mtu else ""

    post_up_lines = [
        f"ip addr add {peer.ipv6_local} peer {peer.ipv6_remote} dev {iface}",
    ]
    if peer.ipv4_local:
        post_up_lines.append(
            f"ip addr add {peer.ipv4_local} peer {peer.ipv4_remote} dev {iface}"
        )
    post_up_lines += [
        f"sysctl -w net.ipv6.conf.{iface}.autoconf=0 || true",
        f"sysctl -w net.ipv4.conf.{iface}.rp_filter=0 || true",
    ]
    post_up = "; ".join(post_up_lines)

    wg_config = f"""[Interface]
PrivateKey = {peer.private_key}
ListenPort = {peer.listen_port}
Table = off
PostUp = {post_up}
{mtu_line}

[Peer]
PublicKey = {peer.public_key}
Endpoint = {peer.endpoint}
AllowedIPs = 10.0.0.0/8, 172.20.0.0/14, 172.31.0.0/16, fd00::/8, fe80::/64
"""
    files.put(
        name=f"Put WireGuard config for {iface}",
        src=StringIO(wg_config),
        dest=f"{wireguard_dir}/{iface}.conf",
    )
    wg_ports.append(peer.listen_port)

# iBGP peers
for peer in dn.ibgp_peers:
    safe = peer.name.replace("-", "_")
    iface = f"dn42_{safe}"

    post_up_lines = [
        f"ip addr add {my_ipv6} peer {peer.ipv6} dev {iface}",
        f"sysctl -w net.ipv6.conf.{iface}.autoconf=0 || true",
        f"sysctl -w net.ipv4.conf.{iface}.rp_filter=0 || true",
    ]
    post_up = "; ".join(post_up_lines)

    listen_port = 10000 + peer.id
    wg_config = f"""[Interface]
PrivateKey = {peer.private_key}
ListenPort = {listen_port}
Table = off
PostUp = {post_up}

[Peer]
PublicKey = {peer.public_key}
Endpoint = {peer.endpoint}
AllowedIPs = 10.0.0.0/8, 172.20.0.0/14, 172.31.0.0/16, fd00::/8, fe80::/64
"""
    files.put(
        name=f"Put WireGuard config for {iface}",
        src=StringIO(wg_config),
        dest=f"{wireguard_dir}/{iface}.conf",
    )
    wg_ports.append(listen_port)

# ============================================================
# Generate BIRD config
# ============================================================

bird_dir = f"{COMPOSE_DIR}/containers/dn42-bird"
ownas = dn.asn
ownip = dn.ipv4_addresses[0] if dn.ipv4_addresses else ""
ownipv6 = dn.ipv6_addresses[0] if dn.ipv6_addresses else ""
ownnetset = ", ".join(n + "+" for n in dn.ipv4_networks)
ownnetset_v6 = ", ".join(n + "+" for n in dn.ipv6_networks)
ownnet_rejects_v4 = "\n        ".join(f"route {n} reject;" for n in dn.ipv4_networks)
ownnet_rejects_v6 = "\n        ".join(f"route {n} reject;" for n in dn.ipv6_networks)

dnet_route = ""
if dn.dnet:
    dnet_route = f"route {dn.ipv4_dnet_address}/32 via \"dnet0\";"

direct_interfaces = 'interface "dn42_*", "dn42dummy0";'
if dn.dnet:
    direct_interfaces = 'interface "dn42_*", "dn42dummy0", "dnet0";'

ebgp_protocols = ""
for name, peer in dn.ebgp_peers.items():
    if peer.asn == ownas:
        continue
    safe = name.replace("-", "_")
    ebgp_protocols += f"""
protocol bgp dn42_{safe} from dnpeers {{
    enable extended messages on;
    neighbor {peer.ipv6_remote}%dn42_{safe} as {peer.asn};
    ipv4 {{
        extended next hop on;
    }};
}};
"""

ibgp_protocols = ""
for peer in dn.ibgp_peers:
    safe = peer.name.replace("-", "_")
    ibgp_protocols += f"""
protocol bgp dn42_{safe} from dnpeers_ibgp {{
    enable extended messages on;
    neighbor {peer.ipv6} as {ownas};
    ipv4 {{
        extended next hop on;
    }};
}}
"""

bird_config = f"""################################################
#               Variable header                #
################################################

define OWNAS = {ownas};
define OWNIP = {ownip};
define OWNIPv6 = {ownipv6};
define OWNNET = {dn.ipv4_networks[0] if dn.ipv4_networks else ""};
define OWNNETv6 = {dn.ipv6_networks[0] if dn.ipv6_networks else ""};
define OWNNETSET = [{ownnetset}];
define OWNNETSETv6 = [{ownnetset_v6}];

################################################
#                 Header end                   #
################################################

router id OWNIP;

protocol device {{
    scan time 10;
}}

protocol direct {{
    ipv4;
    ipv6;
    {direct_interfaces}
}}

function is_self_net() {{
  return net ~ OWNNETSET;
}}

function is_self_net_v6() {{
  return net ~ OWNNETSETv6;
}}

function is_valid_network() {{
  return net ~ [
    172.20.0.0/14{{21,29}},
    172.20.0.0/24{{28,32}},
    172.21.0.0/24{{28,32}},
    172.22.0.0/24{{28,32}},
    172.23.0.0/24{{28,32}},
    172.31.0.0/16+,
    10.100.0.0/14+,
    10.127.0.0/16+,
    10.0.0.0/8{{15,24}}
  ];
}}

function is_valid_network_v6() {{
  return net ~ [
    fd00::/8{{44,64}}
  ];
}}

protocol kernel {{
    scan time 20;
    ipv6 {{
        import none;
        export filter {{
            if source = RTS_STATIC then reject;
            krt_prefsrc = OWNIPv6;
            accept;
        }};
    }};
}};

protocol kernel {{
    scan time 20;
    ipv4 {{
        import none;
        export filter {{
            if source = RTS_STATIC then reject;
            krt_prefsrc = OWNIP;
            accept;
        }};
    }};
}}

protocol static {{
        {ownnet_rejects_v4}
        {dnet_route}

    ipv4 {{
        import all;
        export none;
    }};
}}

protocol static {{
        {ownnet_rejects_v6}

    ipv6 {{
        import all;
        export none;
    }};
}}

template bgp dnpeers {{
    local as OWNAS;
    path metric 1;

    ipv4 {{
        import filter {{
          if is_valid_network() && !is_self_net() then {{
             accept;
          }} else reject;
        }};

        export filter {{ if is_valid_network() && source ~ [RTS_STATIC, RTS_BGP] then accept; else reject; }};
        import limit 9000 action block;
    }};

    ipv6 {{
        import filter {{
          if is_valid_network_v6() && !is_self_net_v6() then {{
             accept;
          }} else reject;
        }};
        export filter {{ if is_valid_network_v6() && source ~ [RTS_STATIC, RTS_BGP] then accept; else reject; }};
        import limit 9000 action block;
    }};
}}

template bgp dnpeers_ibgp {{
    local as OWNAS;
    path metric 1;

    ipv4 {{
        import all;
        export all;
        next hop self;
    }};

    ipv6 {{
        import all;
        export all;
        next hop self;
    }};
}}

protocol bgp ROUTE_COLLECTOR {{
  local as 4242420167;
  neighbor fd42:d42:d42:179::1 as 4242422602;

  multihop;

  ipv4 {{
    add paths tx;
    import none;
    export filter {{
      if ( is_valid_network() && source ~ [ RTS_STATIC, RTS_BGP ] )
      then {{
        accept;
      }}
      reject;
    }};
  }};

  ipv6 {{
    add paths tx;
    import none;
    export filter {{
      if ( is_valid_network_v6() && source ~ [ RTS_STATIC, RTS_BGP ] )
      then {{
        accept;
      }}
      reject;
    }};
  }};
}}

{ebgp_protocols}

{ibgp_protocols}
"""

files.put(
    name="Put bird config",
    src=StringIO(bird_config),
    dest=f"{bird_dir}/bird.conf",
)

# ============================================================
# Generate DNSRecord.h for DNet-core
# ============================================================

dnet_dir = f"{COMPOSE_DIR}/dnet"

if dn.dnet:
    dnet = dn.dnet

    def _ipv6_to_hex(ipv6: str) -> str:
        import ipaddress
        addr = ipaddress.IPv6Address(ipv6)
        return "".join(f"\\x{b:02x}" for b in addr.packed)

    _a_records = ""
    _aaaa_records = ""
    _cname_records = ""
    _txt_records = ""
    for _name, _node in DNET_NODES.items():
        _fqdn = f"{_node['hostname']}.dn42.42420167.xyz"
        if _node["ipv4"]:
            _a_records += f'  REGISTER_A_RECORD("{_fqdn}", "{_node["ipv4"]}");\n'
        if _node["ipv6"]:
            _aaaa_records += f'  REGISTER_GENERIC_RECORD(TYPE_AAAA, "{_fqdn}", 16, "{_ipv6_to_hex(_node["ipv6"])}");\n'
        _cname_records += f'  REGISTER_CNAME_RECORD("{_name}.dn42.42420167.xyz", "{_fqdn}");\n'
        _txt_lines = [
            f'ASN: 4242420167',
            f'Endpoint: {_name}.dn42.42420167.xyz:2xxxx (xxxx is the last 4 digits of your ASN)',
            f'IPv6 LLA: fe80::167',
            f'PubKey: {_node["pub_key"]}',
            f'MP-BGP: enabled',
            f'Extended Next Hop: enabled',
            f'Looking Glass: http://{_name}.dn42.42420167.xyz:5000/',
        ]
        for _line in _txt_lines:
            _escaped = _line.replace("\\", "\\\\").replace('"', '\\"')
            _txt_records += f'  register_txt("{_name}.dn42.42420167.xyz", "{_escaped}");\n'

    _cname_redirect_records = ""
    for _src, _dst in DNET_CNAME.items():
        _cname_redirect_records += f'  REGISTER_CNAME_RECORD("{_src}.dn42.42420167.xyz", "{_dst}.dn42.42420167.xyz");\n'

    _mx_rdata = "\\x00\\x0a\\x04mail\\x04dn42\\x0842420167\\x03xyz\\x00"

    dns_record_h = f"""#ifndef DNET_DNS_RECORD_H
#define DNET_DNS_RECORD_H

#include "DNS.h"
#include <cstring>

void register_dns_records(std::unordered_multimap<record_key, record_value>& dns_records) {{
    REGISTER_GENERIC_RECORD(TYPE_SOA, "42420167.xyz",
        34,
        "\\x03\\x6e\\x73\\x31\\xc0\\x0c\\x05\\x61\\x64\\x6d\\x69\\x6e\\xc0\\x0c\\x78\\xb4\\xe5\\xb1\\x00\\x00\\x1c\\x20\\x00\\x00\\x0e\\x10\\x00\\x01\\x51\\x80\\x00\\x00\\x0e\\x10"
    );
    REGISTER_GENERIC_RECORD(TYPE_NS, "42420167.xyz",
        6,
        "\\x03ns1\\xc0\\x0c"
    );
    REGISTER_GENERIC_RECORD(TYPE_NS, "42420167.xyz",
        6,
        "\\x03ns2\\xc0\\x0c"
    );
    REGISTER_A_RECORD("ns1.42420167.xyz", "188.239.22.57");
    REGISTER_A_RECORD("ns2.42420167.xyz", "188.239.22.57");

    REGISTER_A_RECORD("mail.dn42.42420167.xyz", "188.239.22.57");
    REGISTER_GENERIC_RECORD(TYPE_MX, "dn42.42420167.xyz",
      26,
      "{_mx_rdata}"
    );

{_a_records}{_aaaa_records}{_cname_records}{_cname_redirect_records}
    auto register_txt = [&](const char* name, const char* text) {{
        size_t len = strlen(text);
        char* rdata = new char[len + 1];
        rdata[0] = (char)len;
        memcpy(rdata + 1, text, len);
        REGISTER_GENERIC_RECORD(16, name, len + 1, rdata);
        delete[] rdata;
    }};

{_txt_records}}}
#endif // DNET_DNS_RECORD_H
"""
    files.put(
        name="Put DNSRecord.h for dnet-core",
        src=StringIO(dns_record_h),
        dest=f"{dnet_dir}/DNSRecord.h",
    )

# ============================================================
# Generate Smokeping config
# ============================================================

smokeping_dir = f"{COMPOSE_DIR}/containers/dn42-smokeping"

targets = []
for name, peer in dn.ebgp_peers.items():
    ep = peer.endpoint
    if ep.startswith("["):
        host_addr = ep.split("]")[0][1:]
    else:
        host_addr = ep.split(":")[0]
    asn_last4 = str(peer.asn)[-4:]
    targets.append(f"""
++ DN42_{asn_last4}
menu = DN42 {asn_last4} ({host_addr})
title = DN42 {asn_last4} ({host_addr})
host = {host_addr}""")

for peer in dn.ibgp_peers:
    ep = peer.endpoint
    if ep.startswith("["):
        host_addr = ep.split("]")[0][1:]
    else:
        host_addr = ep.split(":")[0]
    targets.append(f"""
++ {peer.name}
menu = {peer.name} iBGP ({host_addr})
title = {peer.name} iBGP ({host_addr})
host = {host_addr}""")

seen = set()
unique_targets = []
for t in targets:
    host_line = [l for l in t.split("\n") if l.startswith("host = ")]
    if host_line:
        h = host_line[0]
        if h not in seen:
            seen.add(h)
            unique_targets.append(t)

targets_str = "\n".join(unique_targets)

smokeping_db = """*** Database ***

step     = 60
pings    = 10

# consfn mrhb steps total
AVERAGE  0.5   1  5040
AVERAGE  0.5  60  4320
    MIN  0.5  60  4320
    MAX  0.5  60  4320
AVERAGE  0.5 720   720
    MAX  0.5 720   720
    MIN  0.5 720   720
"""

smokeping_presentation = """*** Presentation ***

template = /etc/smokeping/basepage.html

+ charts

menu = Charts
title = The most interesting destinations

++ stddev
sorter = StdDev(entries=>4)
title = Top Standard Deviation
menu = Std Deviation
format = Standard Deviation %f

++ max
sorter = Max(entries=>5)
title = Top Max Roundtrip Time
menu = by Max
format = Max Roundtrip Time %f seconds

++ loss
sorter = Loss(entries=>5)
title = Top Packet Loss
menu = Loss
format = Packets Lost %f

++ median
sorter = Median(entries=>5)
title = Top Median Roundtrip Time
menu = by Median
format = Median RTT %f seconds

+ overview

width = 600
height = 50
range = 10h

+ detail

width = 600
height = 200
unison_tolerance = 2

"Last 3 Hours"    3h
"Last 30 Hours"   30h
"Last 10 Days"    10d
"Last 360 Days"   360d
"""

smokeping_probes = """*** Probes ***

+ FPing
binary = /usr/bin/fping
"""

smokeping_targets = f"""*** Targets ***

probe = FPing

menu = Top
title = Network Latency Grapher
remark = Welcome to the SmokePing website of DN42 Network.

+ DN42Peers
menu = DN42 Peers
title = DN42 Peer Endpoints (External + iBGP)

{targets_str}
"""

files.put(
    name="Put smokeping Database config",
    src=StringIO(smokeping_db),
    dest=f"{smokeping_dir}/Database",
)
files.put(
    name="Put smokeping Presentation config",
    src=StringIO(smokeping_presentation),
    dest=f"{smokeping_dir}/Presentation",
)
files.put(
    name="Put smokeping Probes config",
    src=StringIO(smokeping_probes),
    dest=f"{smokeping_dir}/Probes",
)
files.put(
    name="Put smokeping Targets config",
    src=StringIO(smokeping_targets),
    dest=f"{smokeping_dir}/Targets",
)

# ============================================================
# Generate compose.yaml
# ============================================================

unique_wg_ports = sorted(set(wg_ports))
port_lines = "\n".join(f'      - "{p}:{p}/udp"' for p in unique_wg_ports)

# Build LG servers list with iBGP short names (sgp1, sgp2, ...)
_my_ibgp_name = next(name for name, (_id, _ip, _ipv6, key) in IBGP_NODES.items() if key == dn.private_key)
lg_servers = ",".join(p.name for p in dn.ibgp_peers) + f",{_my_ibgp_name}"

dnet_service = ""
if dn.dnet:
    dnet_service = f"""
  dn42-dnet:
    build: ./containers/dn42-dnet/
    network_mode: "service:dn42-sandbox"
    cap_add: [NET_ADMIN]
    depends_on:
      dn42-network:
        condition: service_completed_successfully
    environment:
      - DNET_IP={dn.dnet.ip}
      - DNET_NETMASK={dn.dnet.netmask}
      - DNET_CIDR={dn.dnet.cidr}
    restart: always"""

ipv4_addresses_str = ", ".join(dn.ipv4_addresses)
ipv6_addresses_str = ", ".join(dn.ipv6_addresses)

dnet_network_env = ""
if dn.dnet:
    dnet_network_env = f"""
      - DN42_DNET_IP={dn.dnet.ip}
      - DN42_DNET_CIDR={dn.dnet.cidr}"""

compose_yaml = f"""networks:
  dn42-net:
    driver: bridge
    ipam:
      config:
        - subnet: 100.64.0.0/24

services:
  dn42-sandbox:
    image: busybox:stable
    container_name: dn42-sandbox
    entrypoint: ["sh", "-c", "tail -f /dev/null"]
    init: true
    networks:
      dn42-net:
        ipv4_address: 100.64.0.2
    ports:
{port_lines}
      - "5000:5000"
      - "5001:5001"
      - "8000:8000"
      - "53:53/udp"
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.rp_filter: 0
      net.ipv4.conf.default.rp_filter: 0
      net.ipv6.conf.all.forwarding: 1
    restart: always

  dn42-network:
    build: ./containers/dn42-network/
    network_mode: "service:dn42-sandbox"
    cap_add: [NET_ADMIN]
    depends_on:
      dn42-sandbox:
        condition: service_started
    environment:
      - DN42_IPV4_ADDRESSES={ipv4_addresses_str}
      - DN42_IPV6_ADDRESSES={ipv6_addresses_str}{dnet_network_env}
    restart: "on-failure"

  dn42-wireguard:
    build: ./containers/dn42-wireguard/
    network_mode: "service:dn42-sandbox"
    cap_add: [NET_ADMIN]
    depends_on:
      dn42-network:
        condition: service_completed_successfully
    restart: always

  dn42-bird:
    build: ./containers/dn42-bird/
    network_mode: "service:dn42-sandbox"
    cap_add: [NET_ADMIN]
    depends_on:
      dn42-wireguard:
        condition: service_started
    volumes:
      - bird_run:/run/bird
    restart: always
{dnet_service}
  dn42-looking-glass:
    build: ./containers/dn42-looking-glass/
    network_mode: "service:dn42-sandbox"
    depends_on:
      dn42-bird:
        condition: service_started
    volumes:
      - bird_run:/run/bird
    environment:
      - LG_SERVERS={lg_servers}
      - LG_DOMAIN=dn42.42420167.xyz
      - LG_FRONTEND_PORT=5000
    restart: unless-stopped

  dn42-smokeping:
    build: ./containers/dn42-smokeping/
    network_mode: "service:dn42-sandbox"
    depends_on:
      dn42-sandbox:
        condition: service_started
    restart: unless-stopped

volumes:
  bird_run:
"""

files.put(
    name="Put compose.yaml",
    src=StringIO(compose_yaml),
    dest=f"{COMPOSE_DIR}/compose.yaml",
)

# Copy generated DNSRecord.h into dnet build context for docker build
if dn.dnet:
    files.put(
        name="Copy DNSRecord.h into dnet build context",
        src=StringIO(dns_record_h),
        dest=f"{COMPOSE_DIR}/containers/dn42-dnet/DNSRecord.h",
    )

# ============================================================
# Deploy with docker compose
# ============================================================

server.shell(
    name="Deploy DN42 containers",
    commands=[
        f"cd {COMPOSE_DIR} && docker compose up -d --build --remove-orphans",
    ],
)
