- name: Install hd-idle
  apt:
    name: hd-idle
    state: present
    update_cache: yes

- name: Configure hd-idle
  template:
    src: hd-idle
    dest: /etc/default/hd-idle
    owner: root
    group: root
    mode: 0644
  notify: Restart hd-idle

- name: Start hd-idle
  service:
    name: hd-idle
    state: started
    enabled: yes
