# Netdata v2.0.0 is shit, pin to old version https://www.reddit.com/r/selfhosted/comments/1hae2eq/monitoring_tool_netdata_v20_is_limiting_the/
- name: Make sure lm-sensors is installed
  apt:
    name: lm-sensors
    state: present
    update_cache: yes

- name: Gather package facts
  package_facts:
    manager: apt

- name: Create cache directory
  file:
    state: directory
    path: /tmp/netdata_deb/
  when: '"netdata" not in ansible_facts.packages'

- name: Fetch Netdata DEB
  ansible.builtin.get_url:
    url: "{{item}}"
    dest: /tmp/netdata_deb/{{ item | basename }}
    mode: 0644
  when: '"netdata" not in ansible_facts.packages'

  environment:
    https_proxy: http://192.168.1.51:7890/
  loop:
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-apps_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-chartsd_1.47.5+debian12_all.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-cups_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-debugfs_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-ebpf_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-freeipmi_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-go_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-network-viewer_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-nfacct_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-perf_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-pythond_1.47.5+debian12_all.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-slabinfo_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-systemd-journal_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata-plugin-xenstat_1.47.5+debian12_amd64.deb
    - https://github.com/lyc8503/infra/releases/download/netdata/netdata_1.47.5+debian12_amd64.deb

- name: Install Netdata from archive
  ansible.builtin.shell:
    cmd: apt install -y /tmp/netdata_deb/*.deb
  when: '"netdata" not in ansible_facts.packages'

- name: Clean up Netdata DEB
  ansible.builtin.file:
    state: absent
    path: /tmp/netdata_deb/

- name: Template Netdata configuration
  template:
    src: netdata.conf
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: u=wrx,g=rx,o=r,+x
  notify: Restart Netdata

- name: Setup Netdata metrics aggregation
  template:
    src: aggregator.chart.py
    dest: /usr/libexec/netdata/python.d/aggregator.chart.py
    owner: root
    group: netdata
    mode: u=rw,g=r,o=r
  notify: Restart Netdata

- name: Install MI IOT dependencies
  ansible.builtin.shell:
    cmd: pip3 install -t . git+https://github.com/rytilahti/python-miio.git
    creates: /usr/libexec/netdata/python.d/python_modules/miio/__init__.py
    chdir: /usr/libexec/netdata/python.d/python_modules/

- name: Setup MI IOT power consumption plugin
  template:
    src: miiot_power.chart.py
    dest: /usr/libexec/netdata/python.d/miiot_power.chart.py
    owner: root
    group: netdata
    mode: u=rw,g=r,o=r
  notify: Restart Netdata

- name: Setup custom dashboard
  template:
    src: mydash.html
    dest: /usr/share/netdata/web/mydash.html
    owner: root
    group: netdata
    mode: u=rw,g=r,o=r
  notify: Restart Netdata
