- name: Install Alloy
  ansible.builtin.include_role:
    name: grafana.grafana.alloy
  vars:
    alloy_config: |
      prometheus.exporter.unix "local_system" {
        disable_collectors = ["systemd"]
      }

      prometheus.scrape "scrape_metrics" {
        targets = prometheus.exporter.unix.local_system.targets
        forward_to = [prometheus.relabel.filter_metrics.receiver]
      }

      prometheus.relabel "filter_metrics" {
        forward_to = [prometheus.remote_write.prom.receiver]
      }

      prometheus.remote_write "prom" {
        endpoint {
          url = "{{ push_endpoint }}"
        }
      }

      loki.source.journal "read"  {
        forward_to    = [loki.write.endpoint.receiver]
        labels        = {component = "{{ ansible_hostname }}"}
      }

      loki.write "endpoint" {
        endpoint {
          url = "{{ loki_endpoint }}"
        }
      }
