- include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: uvicorn
      - name: fastapi
      - name: requests

- name: Copy systemd config
  template:
    src: sub.service
    dest: /etc/systemd/system/sub.service
  notify:
    - Restart sub

- name: Copy code
  copy:
    src: sub.py
    dest: /root/sub.py
  notify:
    - Restart sub

- name: Start sub service
  systemd:
    name: sub
    state: started
    daemon_reload: yes
    enabled: yes
