---
- include_role:
    name: geerlingguy.docker
- include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose

- name: Ensure directory exists
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}"
    state: directory

- name: Copy compose file
  template:
    src: docker-compose.yml
    dest: "{{ docker_compose_dir }}/compose.yaml"
  notify:
    - Docker compose up
    - Prune everything (including non-dangling images)

- name: Copy other files
  copy:
    src: "."
    dest: "{{ docker_compose_dir }}/"
  notify:
    - Docker compose up
    - Prune everything (including non-dangling images)
