---
- include_role:
    name: geerlingguy.docker
- include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose

- name: Ensure directory exists
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}"
    state: directory

- name: Copy compose file
  template:
    src: docker-compose.yml
    dest: "{{ docker_compose_dir }}/compose.yaml"

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
    remove_orphans: true

- name: Prune everything (including non-dangling images)
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true
