---
- name: Install unzip and jq
  package:
    name:
      - unzip
      - jq
    state: present

- name: Install register script
  template:
    src: register.sh
    dest: /opt/register.sh
    mode: "0755"

- name: Setup cron job
  cron:
    name: Register xray
    minute: "*/5"
    job: /opt/register.sh
    state: present

- name: Ensure directory exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/xray
    - /etc/xray

- name: Get xray binary package
  unarchive:
    src: "https://github.com/XTLS/Xray-core/releases/download/v{{ app_ver }}/Xray-linux-{{ app_arch }}.zip"
    dest: /opt/xray
    remote_src: yes

- name: Symlink binary files
  file:
    src: "/opt/xray/xray"
    dest: "/usr/bin/xray"
    state: link

- name: Generate xray config
  template:
    src: config.json.j2
    dest: /etc/xray/config.json
  notify:
    - Restart xray

- name: Copy systemd config
  copy:
    src: xray.service
    dest: /etc/systemd/system/xray.service

- name: Start xray service
  systemd:
    name: xray
    state: started
    daemon_reload: yes
    enabled: yes
