# Proxy servers (cloudflared tunnel)
# IPv6 only servers need to setup WARP, refer to https://p3terx.com/archives/use-cloudflare-warp-to-add-extra-ipv4-or-ipv6-network-support-to-vps-servers-for-free.html
# Usage: It just works, even doesn't need a domain.
# Will allocate a random subdomain from trycloudflare.com and register itself to sub server.
- name: Setup proxy servers
  hosts: proxy_servers

  roles:
    - v2ray # proxy server (dedicated, ws mode)
    - cloudflared # cloudflared for tunnel ws
    - metrics # prometheus node exporter and alloy

# Proxy servers (direct connection)
- name: Setup direct proxy servers
  hosts: direct_proxy_servers
  roles:
    - xray # proxy server (dedicated, xray reality vision and grpc)
    - hysteria2
    # - metrics # prometheus node exporter and alloy

- name: Setup metrics-only servers
  hosts: metrics_only
  roles:
    - metrics # prometheus node exporter and alloy
