- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Global Vim configuration
  ansible.builtin.template:
    src: vimrc
    dest: /etc/vim/vimrc.local
    owner: root
    group: root
    mode: 0644
