version: "3"

services:
  ddddocr:
    image: lyc8503/ddddocr:v1
    restart: unless-stopped
    ports:
      - "127.0.0.1:9898:80"
  
  sub:
    build: ./sub
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - ADMIN_PASSWORD={{ sub_password }}
      - REG_PASSWORD={{ reg_password }}

  tgbot:
    build: ./TGBot
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:8000"
    environment:
      - BOT_TOKEN={{ bot_token }}
      - CHAT_ID={{ chat_id }}
      - PUSH_KEY={{ push_key }}
      - SELF_URL={{ self_url }}
      - SECRET_TOKEN={{ secret_token }}
    volumes:
      - /opt/nju.txt:/app/nju.txt
