version: "3"

services:
  sub:
    build: ./sub
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - ADMIN_PASSWORD={{ sub_password }}
      - REG_PASSWORD={{ reg_password }}

  tgbot:
    build: ./TGBot
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:8000"
    environment:
      - BOT_TOKEN={{ bot_token }}
      - CHAT_ID={{ chat_id }}
      - PUSH_KEY={{ push_key }}
      - SELF_URL={{ self_url }}
      - SECRET_TOKEN={{ secret_token }}
    volumes:
      - /opt/nju.txt:/app/nju.txt

  tgrss:
    image: rongronggg9/rss-to-telegram:dev  # stable image: rongronggg9/rss-to-telegram
    restart: unless-stopped
    volumes:
      - /opt/tgrss:/app/config
    environment:
      - TOKEN={{ rss_bot_token }}
      - MANAGER={{ rss_manager }}
  
  log_forward:
    build: ./log_forward
    restart: unless-stopped
    environment:
      - LOKI_TOKEN={{ loki_token }}
