server {
    listen 5001;
    listen [::]:5001;
    server_name _;

    root /usr/share/smokeping/www;
    index smokeping.cgi;

    location /smokeping/smokeping.cgi {
        include fastcgi_params;
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        fastcgi_param SCRIPT_FILENAME /usr/lib/cgi-bin/smokeping.cgi;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location /smokeping/ {
        alias /usr/share/smokeping/www/;
        index smokeping.cgi;
    }

    location / {
        rewrite ^/$ /smokeping/smokeping.cgi redirect;
    }
}
